### ISSUE TITLE
GeoEnrichmentWidget in the Native Operations Dashboard

### ISSUE THREAD

**Issue by jofraley** [Esri/dashboard-samples#2] opened 2015-08-12 15:45 UTC
I am getting an error in the dev mode with the geoenrichmentwidget that it has an issue with a shorterm token.  And the task never executes.  It works fine in the browser.  I also tried publishing to a web server and still does not execute in the native ops dashboard.  Does the web server have to be SSL for this to work in the native dashboard?

**Comment by TifPun** [comment] 2015-09-09 22:01
Thanks @jofraley we will investigate on this issue. Meanwhile could you try the following: If you register the widget into your org and then bring it into your native Dashboard, do you still see the problem?

**Comment by jofraley** [comment] 2015-09-10 17:12
@TifPun When I do what you suggested above the widget loads but when I click on the map but the widget just spins and never returns the graph.

**Comment by TifPun** [comment] 2015-09-10 17:33
Thanks @jofraley I am able to repro this problem in my machine. We will take a look at that.

**Comment by TifPun** [comment] 2015-11-04 02:00
@jofraley We confirmed that the issue is caused by a bug in native Dashboard. The fix for the bug will go in to the upcoming release. Please let us know if you still run into issues using the geoenrichment widget.

**Comment by TifPun** [comment] 2015-12-14 18:53
We've verified that this issue is fixed using the latest version of desktop Operations Dashboard (10.3.2.1154). Closing out this issue.

**Closed as completed by TifPun** 2015-12-14 18:53 UTC
